### ISSUE TITLE
Cant retrieve the links

### ISSUE THREAD

**Issue by voltrare** [ufe-pr/anime#1]
1.      Darwin's Game
Enter ur anime number: 1
There are 11 episodes for this anime
Download links will be saved in links\darwins-game.txt
Traceback (most recent call last):
  File "Animescrape.py", line 44, in <module>
    main()
  File "Animescrape.py", line 34, in main
    down_link = get_down_link(embed_link)
  File "C:\winpython\downloader\anime\functions.py", line 74, in get_down_link
    form_data = {'_token': get_token(kwik_link)}
  File "C:\winpython\downloader\anime\functions.py", line 67, in get_token
    token = re.search(r'name\|_token\|value\|(\w+)\|submit', res).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\winpython\downloader\anime>

**Comment by ufe-pr** [comment]
Kwik has added captcha in their veificaiton process..so I don't know if there's anything i can do

**Comment by thaynos** [comment]
i have the same problem :(
i took me so long to download this (im nub) and now i see this message 😭

**Comment by ufe-pr** [comment]
> i have the same problem :(
> i took me so long to download this (im nub) and now i see this message 😭

Very sorry about this 🙏. The project was actually discontinued but you can use this telegram bot [@animehive_bot](https://telegram.me/animehive_bot) to get direct download links for now.

**Comment by voltrare** [comment]
thank you for your work
